# Generated by Django 5.0.6 on 2024-06-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('em andamento', 'Em Andamento'), ('concluído', 'Concluído')], default='em andamento', max_length=20),
        ),
    ]
