# Generated by Django 5.0.6 on 2024-06-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_projeto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='em_andamento', max_length=20),
        ),
    ]
